version: '3'
services:
  web:
    build: ./flask_service
    ports:
      - "8080:80"
    volumes:
      - ./flask_service/src:/app/src
    environment:
      MONGO_IP: 192.168.0.59
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD: example

  gen:
    build: ./gen_service
    volumes:
      - ./gen_service/src:/app/src
    environment:
      MONGO_IP: 192.168.0.59
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD: example
      POPULATION_SIZE: 10000
      MAX_GENERATION: 1000

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
