version: '3'
services:
#  web:
#    build: ./flask_service
#    ports:
#      - "8080:80"
#    volumes:
#      - ./flask_service/src:/app/src
#    environment:
#      MONGO_IP: 192.168.0.59
#      MONGO_PORT: 27017
#      MONGO_USER: root
#      MONGO_PASSWORD: example

  gen:
    build: ./gen_service
    volumes:
      - ./gen_service/src:/app/src
    environment:
      DATA_CONNECTOR_TYPE: mongodb
      DATA_CONNECTOR_IP: 192.168.0.59
      DATA_CONNECTOR_PORT: 27018
      DATA_CONNECTOR_USER: root
      DATA_CONNECTOR_PASSWORD: example
      DATABASE_NAME: data
      COLLECTION_NAME: data
#      TABLE_NAME: data
      POPULATION_SIZE: 100
      MAX_GENERATION: 1000
